CREATE TABLE posts (
id SERIAL PRIMARY KEY,
match_id INT REFERENCES matches(id) ON DELETE CASCADE,
post VARCHAR NOT NULL,
poster INT REFERENCES members(id) ON DELETE CASCADE,
time_stamp TIMESTAMP DEFAULT NOW()
);